trigger:
- main

pool:
  name: Linux-Build-Agents

jobs:

# ---------------- UNIT TESTS ----------------
- job: UnitTests
  displayName: "Unit Tests"

  steps:
  - checkout: self

  - script: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip python3-venv

      python3 -m venv venv
      source venv/bin/activate

      pip install --upgrade pip
      pip install -r requirement.txt

      python -m pytest tests/test_unit.py
    displayName: "Run Unit Tests"


# ---------------- FUNCTIONAL TESTS ----------------
- job: FunctionalTests
  displayName: "Functional Tests"

  steps:
  - checkout: self

  - script: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip python3-venv

      python3 -m venv venv
      source venv/bin/activate

      pip install --upgrade pip
      pip install -r requirement.txt

      python -m pytest tests/test_functional.py
    displayName: "Run Functional Tests"


# ---------------- DOCKER BUILD ----------------
- job: DockerBuild
  displayName: "Build Docker Image"

  dependsOn:
  - UnitTests
  - FunctionalTests

  condition: succeeded()

  steps:
  - checkout: self

  - script: |
      sudo apt-get update
      sudo apt-get install -y docker.io

      sudo systemctl start docker

      docker --version
    displayName: "Install Docker"

  - script: |
      sudo docker build -t fastapi-math-api .
      sudo docker images
    displayName: "Build Docker Image"